services:
  swaranangdb:
    container_name: swaranangdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: swaranang_db
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-db-config

  rabbit:
    image: rabbitmq:3.12-management
    container_name: rabbit-mq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "nizen25/configserver:1.0"
    container_name: configserver-ms
    restart: no
    ports:
      - "9000:9000"
      - "5001:5001"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config


  swaranang:
    image: "nizen25/swaranang-magorula-society:1.0"
    container_name: swaranang-ms
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "swaranang"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  gqmessaging:
    image: "nizen25/gq-messaging-api:1.0"
    container_name: gq-messaging-ms
    ports:
      - "1000:1000"
      - "4004:4004"
    environment:
      SPRING_APPLICATION_NAME: "gq-messaging-api"
      SPRING_PROFILES_ACTIVE: "default"
    extends:
      file: common-config.yml
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  gqeventsdb:
    container_name: gqeventsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: gq_event_tickets_db
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-db-config

  gqevents:
    image: "nizen25/gq-event-management:1.0"
    container_name: gq-events-ms
    ports:
      - "8000:8000"
      - "5006:5006"
    extends:
      file: common-config.yml
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    depends_on:
      gqeventsdb:
        condition: service_healthy

networks:
  nizen25:
    driver: "bridge"